### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by 49b** [freemyipod/wInd3x#6]
Hi, every few days there was an update to this repository, but suddenly, the repository did not get updated for a month. Is the project dead?

**Comment by 49b** [comment]
In case no one saw this issue: @q3k @user890104

**Comment by q3k** [comment]
I'm not exactly sure what sort of answer you're looking for.

**Comment by user890104** [comment]
It's a hobby project, and when we achieve any progress, we push it to the repo and/or post in wiki/twitter/IRC/matrix.

**Comment by 49b** [comment]
I was just asking if this project is no longer maintained or not. I'm sorry for disturbing.

> I'm not exactly sure what sort of answer you're looking for.

**Comment by user890104** [comment]
You can hang around, if you're interested in iPod-releated R&D: https://freemyipod.org/wiki/Contact
